name: Workrave build containers

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/workrave-build

jobs:
  build_linux:
    name: Linux ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian-testing
          - ubuntu-pbuilder
          - ubuntu-jammy
          - ubuntu-noble
          - ubuntu-questing
          - ubuntu-resolute
    uses: ./.github/workflows/build-linux-image.yml
    with:
      image: ${{ matrix.image }}
    secrets: inherit

  build_on_windows:
    runs-on: windows-2022
    name: Windows Image ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: windows-msys2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/workrave-build:${{ matrix.image }} --build-arg=GIT_COMMIT_HASH=${{ github.sha }} ./${{ matrix.image }}/

      - name: Publish
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/workrave-build:${{ matrix.image }}
